version: "3"

services:
  tests:
    image: todotests:latest
    environment:
      - FRONT_HOST=front
    depends_on:
      - 'todofront'
      - 'todoback'

  todofront:
    image: todofrontend:latest
    environment:
      - REACT_APP_API_HOST=back
    ports:
      - 3000:3000
    depends_on:
      - 'todoback'

  todoback:
    image: todobackend:latest
    ports:
      - 3001:3001

  
